### Working with Intrinio Data - Test Program

In [63]:
# Imports 

# IO Imports
import requests
import pprint
from pandas.io.json import json_normalize

# Data Imports
import numpy as np
import pandas as pd
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [72]:
# Code provided by Intrinio Customer Service to get started

# Credentials for Intrinio
with open('intriniocred.txt') as cred:
    api_username,api_password = cred.readlines()

api_username = api_username.strip()
api_password = api_password.strip()

# Stock ticker
ticker = "ATVI"

# Create list of dates
fundamentals_url = "https://www.intrinio.com/api/fundamentals/standardized"
p = {'ticker':ticker,'statement':'income_statement','type':'FY'}
r = requests.get(fundamentals_url, params=p, auth=(api_username, api_password))
date_list = r.json()['data']
print(len(date_list))

# Import data
statement_url = "https://www.intrinio.com/api/financials/standardized"

col_list = ['item']
test1 = False

for date_list_element in date_list:
    dd = date_list_element['end_date']
    col_list.append(dd)
    p = {'ticker':ticker,'statement':'income_statement','type':'FY','date':dd}
    r = requests.get(statement_url, params=p, auth=(api_username, api_password))
    if test1 == False:
        is_df = json_normalize(r.json()['data'])
        test1 = True
    else:
       is_df = is_df.merge(json_normalize(r.json()['data']),how='outer',on='tag',)

is_df.columns = [col_list]
is_df

9

,item,2015-12-31,2014-12-31,2013-12-31,2012-12-31,2011-12-31,2010-12-31,2009-12-31,2008-12-31,2007-12-31
0,operatingrevenue,4664000000.000,4408000000.000,4583000000.000,4856000000.000,4755000000.000,4447000000.000,4279000000.000,3026000000.000,1349000000.000
1,totalrevenue,4664000000.000,4408000000.000,4583000000.000,4856000000.000,4755000000.000,4447000000.000,4279000000.000,3026000000.000,1349000000.000
2,operatingcostofrevenue,1585000000.000,1525000000.000,1531000000.000,1662000000.000,1772000000.000,2135000000.000,2307000000.000,1839000000.000,436000000.000
3,totalcostofrevenue,1585000000.000,1525000000.000,1531000000.000,1662000000.000,1772000000.000,2135000000.000,2307000000.000,1839000000.000,436000000.000
4,totalgrossprofit,3079000000.000,2883000000.000,3052000000.000,3194000000.000,2983000000.000,2312000000.000,1972000000.000,1187000000.000,913000000.000
5,sgaexpense,1114000000.000,1129000000.000,1096000000.000,1139000000.000,1001000000.000,891000000.000,939000000.000,735000000.000,338000000.000
6,rdexpense,646000000.000,571000000.000,584000000.000,604000000.000,629000000.000,626000000.000,627000000.000,592000000.000,397000000.000
7,totaloperatingexpenses,1760000000.000,1700000000.000,1680000000.000,1743000000.000,1655000000.000,1843000000.000,1998000000.000,1420000000.000,734000000.000
8,totaloperatingincome,1319000000.000,1183000000.000,1372000000.000,1451000000.000,1328000000.000,469000000.000,-26000000.000,-233000000.000,179000000.000
9,otherincome,-198000000.000,-202000000.000,-53000000.000,7000000.000,3000000.000,nan,nan,nan,nan
10,totalotherincome,-198000000.000,-202000000.000,-53000000.000,7000000.000,3000000.000,23000000.000,18000000.000,46000000.000,-4000000.000
11,totalpretaxincome,1121000000.000,981000000.000,1319000000.000,1458000000.000,1331000000.000,492000000.000,-8000000.000,-187000000.000,175000000.000
12,incometaxexpense,229000000.000,146000000.000,309000000.000,309000000.000,246000000.000,74000000.000,-121000000.000,-80000000.000,-52000000.000
13,netincomecontinuing,892000000.000,835000000.000,1010000000.000,1149000000.000,1085000000.000,418000000.000,113000000.000,-107000000.000,227000000.000
14,netincome,892000000.000,835000000.000,1010000000.000,1149000000.000,1085000000.000,418000000.000,113000000.000,-107000000.000,227000000.000
15,netincometocommon,892000000.000,835000000.000,1010000000.000,1149000000.000,1085000000.000,418000000.000,113000000.000,-107000000.000,227000000.000
16,weightedavebasicsharesos,728000000.000,716000000.000,1024000000.000,1112000000.000,1148000000.000,1222000000.000,1283000000.000,946000000.000,591000000.000
17,basiceps,1.210,1.140,0.960,1.010,0.930,0.340,0.090,-0.110,0.380
18,weightedavedilutedsharesos,739000000.000,726000000.000,1035000000.000,1118000000.000,1156000000.000,1236000000.000,1311000000.000,946000000.000,591000000.000
19,dilutedeps,1.190,1.130,0.950,1.010,0.920,0.330,0.090,-0.110,0.380
20,weightedavebasicdilutedsharesos,737200000.000,732500000.000,1052100000.000,1137600000.000,1166700000.000,1229400000.000,1255600000.000,972700000.000,597400000.000
21,basicdilutedeps,1.210,1.140,0.960,1.010,0.930,0.340,0.090,-0.110,0.380
22,cashdividendspershare,0.230,0.200,0.190,0.180,0.165,0.150,0.000,0.000,nan
23,restructuringcharge,nan,nan,nan,nan,25000000.000,0.000,23000000.000,93000000.000,-1000000.000
24,impairmentexpense,nan,nan,nan,nan,nan,326000000.000,409000000.000,0.000,nan
25,totalinterestincome,nan,nan,nan,nan,nan,23000000.000,18000000.000,46000000.000,-4000000.000